onboarding = false
[update]
channel = "preview"

[terminal]
default_shell = "nu"

[ui]
agent_panel_scope = "all"

[theme]
name = "catppuccin"

[ui.sound]
enabled = false

[keys]
prefix = "ctrl+b"
new_tab = "prefix+c"
